Ini, TOML

[package]
name = "ipfs_client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ipfs_client"
path = "src/main.rs"


[dependencies]
ipfs-api-backend-actix = "0.7"

[dev-dependencies]
cargo-run = "^0.4" # To run examples (optional)
